name: signaling_server
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^6.0.0
